/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cutestvet.IGU;

import com.mycompany.cutestvet.Logica.Controladora;
import com.mycompany.cutestvet.Logica.Dog;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author crist
 */
public class ViewClients extends javax.swing.JFrame {

    //INSTANCIA GLOBAL CONTROLADORA
    Controladora control = null;
    public ViewClients() {
        
        control = new Controladora();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableContent = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnDeleteClient = new javax.swing.JButton();
        btnEditClient = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setText("VIEW EXISTENT CLIENTS");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\crist\\OneDrive\\Escritorio\\Veterinaria\\icon.png")); // NOI18N

        tableContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableContent);

        btnDeleteClient.setBackground(new java.awt.Color(71, 194, 221));
        btnDeleteClient.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnDeleteClient.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteClient.setText("DELETE CLIENT");
        btnDeleteClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteClientActionPerformed(evt);
            }
        });

        btnEditClient.setBackground(new java.awt.Color(71, 194, 221));
        btnEditClient.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnEditClient.setForeground(new java.awt.Color(255, 255, 255));
        btnEditClient.setText("EDIT CLIENT");
        btnEditClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClientActionPerformed(evt);
            }
        });

        btnReturn.setBackground(new java.awt.Color(57, 185, 91));
        btnReturn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("RETURN");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnEditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteClient, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditClient, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        //CUANDO SE LLAME A ESTA VENTANA QUE AUTOMATICAMENTE SE LLAME A UN 
        //METODO QUE ME CARGE LOS CLIENTES EXISTENTES
        uploadTable();
    }//GEN-LAST:event_formWindowOpened

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        //CERRAR LA VENTANA Y VOLVER HACIA ATRAS
        this.dispose();
    }//GEN-LAST:event_btnReturnActionPerformed

    private void btnDeleteClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteClientActionPerformed
        
        /*ELIMINAR UN CLIENTE POR EL ID, SI NO HAY NADA SELECCIONADO 
O SI LA TABLA ESTA VACIA, QUE NO PUEDA ELIMINARSE NADA
        SI LA FILA SELECCIONADA NO ESTA VACIA O EL CONTEO ES MAYOR A CERO
        ES DECIR QUE AL MENOS TIENE QUE HABER UN REGISTRO EN LA BASE DE DATOS*/
        if(tableContent.getRowCount() > 0){
            //TAMBIEN TIENE QUE HABER AL MENOS UNO SELECCIONADO ES DECIR DIFERENTE A -1
            if(tableContent.getSelectedRow() !=-1){
                /*GUARDO EN UNA VARIABLE AUXILIAR EL IDCLIENTE QUE TENGO EN LA
                POSICION CERO, RECORDAR QUE EL VALOR ESTA DECLARADO COMO UN OBJETO, 
                POR LO CUAL SE EXTRAE COMO STRING Y LUEGO SE PARSEA A INTEGER PARA 
                PODER SER GUARDADO COMO UN ENTERO
                */
                int idCliente = Integer.parseInt(String.valueOf(tableContent.getValueAt(tableContent.getSelectedRow(), 0)));
                
                //CREAR EL METODO EN LA CONTROLADORA PASANDOLE EL IDCLIENTE A BORRAR
                control.borrar(idCliente);
                //NOTIFICACION DE BORRADO EXITOSO
                notificacion("DELETE CLIENTE SUSSES", "INFO", "200 OK ");
                //LLAMO AL METODO CARGAR TABLA PARA QUE ACTUALIZE EL CONTENIDO UNA VEZ ELIMINADO EL CLIENTE
                uploadTable();
            }else{
                notificacion("NO SELECT CLIENT", "ERROR", "404 BAD REQUEST");
            }
        }else{
            notificacion("NO EXIST ANY CLIENT", "ERROR", "404 BAD REQUEST");
        }
        
    }//GEN-LAST:event_btnDeleteClientActionPerformed

    private void btnEditClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClientActionPerformed
        // EDITAR EL CLEINTE QUE TENGAMOS MARCADO EN EL TABLE CONTENT
        //SI LA FILA SELECCIONADA NO ESTA VACIA, TIENE QUE HABER AL MENOS UN REGISTRO > 0
        if(tableContent.getRowCount() > 0){
            //TIENE QUE HABER AL MENOS UNA FILA SELECCIONADA
            if(tableContent.getSelectedRow() !=-1){
                //OBTENGO EL ID DE LA MASCOTA A EDITAR
                int idCliente = Integer.parseInt(String.valueOf(tableContent.getValueAt(tableContent.getSelectedRow(), 0)));
                
                //LLAMO A UNA INSTANCIA DE LA PANTALLA EDITAR CLIENTE PASANDOLE EL ID CLIENTE SELECCIONADO
                EditClient editar = new EditClient(idCliente);
                editar.setVisible(true);
                editar.setLocationRelativeTo(null);
                //CUANDO LLAMO A LA PANTALLA EDITAR, HAGO QUE LA VENTANA VER CLIENTES SE CIERREA
                this.dispose();
                
                
            }else{
                notificacion("NO SELECT ANY CLIENT", "ERROR", "404 BAD REQUEST");
            }
        }else{
            notificacion("NO ANY CLIENT IN DATE BASE", "ERROR", "404 BAD REQUEST");
        }
    }//GEN-LAST:event_btnEditClientActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteClient;
    private javax.swing.JButton btnEditClient;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableContent;
    // End of variables declaration//GEN-END:variables

    private void uploadTable() {
        //DEFINIR EL MODELO QUE QUEREMOS QUE TENGA LA TABLA
        DefaultTableModel tableModel = new DefaultTableModel(){
            //CONFIGURAR QUE LA TABLA NO PUEDA SER EDITADA POR ERROR DEL USUARIO
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        //ESTABLECER LOS NOMBRES QUE DEVEN TENER LAS COLUMNAS QUE SE CREARAN EN LA TABLA
        //LAS CREAMOS COMO UN VECTOR Y LUEGO SE LAS ASIGNAMSO A TABLEMODEL
        String titles[] = {"Id", "Dog", "Breed", "Color", "Allergies", 
        "Esp.Aten.", "Owner", "Phone", "Address", "Notes"};
        
        tableModel.setColumnIdentifiers(titles);
        
        //CREAR UN METODO PARA QUE LEVANTE LOS DATOS DE DOGS DESDE LA BASE DE DATOS
        List<Dog> listDogs = control.findDogsEntitites();
        
        //RECORRER LA LISTA QUE ESTA TRALLENDO EL METODO DESDE LA BASDE DE DATOS
        //Y SETTEARSELA A LA TABLE MODEL
        if( listDogs != null){
            for(Dog dog:listDogs){
                Object[] object = {dog.getIdDog(), dog.getNameDog(),
                dog.getBreedDog(), dog.getColorDog(), dog.getAllergicDog(), 
                dog.getEspAtDog(), dog.getOwner().getNameOwner(),
                dog.getOwner().getPhoneOwner(), dog.getOwner().getAddressOwner(),
                dog.getNotesDog()};
                
                //ASIGNAR LOS DATOS DE UN BUCLE A UNA FILA DE LA TABLE MODEL
                tableModel.addRow(object);
            }
        }
        //UNA VEZ QUE HAGA TODOS LOS BUCLES, LE ASIGNAMOS ESTOS PARAMETROS A LA TABLE CONTENT
        //ES EL NOMBRE DE VARIABLE QUE LE COLOCAMOS A LA VARIABLE EN EL DESIGN
        tableContent.setModel(tableModel);
        
        
        

    }
    
    
    //MENSAJE DE NOTIFICACION
    public void notificacion(String mensaje, String tipoMensaje, String titulo){
        JOptionPane optionPane = new JOptionPane(mensaje);
        if(tipoMensaje.equalsIgnoreCase("INFO")){
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        }else if(tipoMensaje.equalsIgnoreCase("ERROR")){
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        JDialog dialog = optionPane.createDialog(titulo);
        dialog.setAlwaysOnTop(true);
        dialog.setVisible(true);
    }
    
}
